export const recipes = [
  {
    id: 1,
    name: "Jollof Rice",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 60,
    difficulty: 'Medium' as const,
    category: "West African",
    description: "A popular West African rice dish cooked in a flavorful tomato sauce.",
    ingredients: ["2 cups long-grain rice", "1 can crushed tomatoes", "1 onion", "2 cloves garlic", "1 tsp thyme", "1 tsp curry powder", "1 cup vegetable oil", "Salt to taste"],
    instructions: [
      "Blend tomatoes, onions, and garlic into a smooth puree",
      "Heat oil in a large pot and fry the puree for 10-15 minutes",
      "Add spices and continue cooking for 5 minutes",
      "Add rice and stir until well coated",
      "Add 2 cups of water, cover and simmer for 30 minutes or until rice is cooked",
      "Fluff with a fork and serve hot"
    ],
  },
  {
    id: 2,
    name: "Pap and Chakalaka",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 30,
    difficulty: 'Easy' as const,
    category: "South African",
    description: "A South African staple of cornmeal porridge served with spicy vegetable relish.",
    ingredients: ["2 cups white cornmeal", "4 cups water", "1 can baked beans", "1 onion", "1 bell pepper", "2 carrots", "2 tomatoes", "1 tsp curry powder", "Salt to taste"],
    instructions: [
      "For the pap: Bring water to a boil, slowly add cornmeal while stirring. Reduce heat and simmer for 20 minutes",
      "For the chakalaka: Chop vegetables and sauté in oil",
      "Add curry powder and baked beans, simmer for 10 minutes",
      "Serve pap with chakalaka on top"
    ],
  },
  {
    id: 3,
    name: "Fufu and Egusi Soup",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 90,
    difficulty: 'Hard' as const,
    category: "West African",
    description: "A West African staple of pounded cassava dough served with a rich, nutty soup.",
    ingredients: ["2 cups cassava flour", "1 cup hot water", "1 cup ground egusi seeds", "1 lb beef or goat meat", "2 cups chopped spinach", "1 onion", "2 tbsp palm oil", "Salt and pepper to taste"],
    instructions: [
      "Mix cassava flour with hot water to form a dough, knead until smooth",
      "For the soup: Brown meat in palm oil, add onions and cook until soft",
      "Add egusi seeds and cook for 10 minutes",
      "Add water to cover, simmer for 30 minutes",
      "Add spinach and cook for 5 more minutes",
      "Serve fufu with egusi soup"
    ],
  },
  {
    id: 4,
    name: "Bobotie",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 75,
    difficulty: 'Medium' as const,
    category: "South African",
    description: "A South African dish of spiced minced meat baked with an egg-based topping.",
    ingredients: ["2 lbs ground beef", "2 slices bread", "1 cup milk", "2 eggs", "1 onion", "2 tbsp curry powder", "1/4 cup raisins", "2 tbsp chutney", "Salt and pepper to taste"],
    instructions: [
      "Soak bread in milk, then mix with ground beef, onion, and spices",
      "Add raisins and chutney, mix well",
      "Place mixture in a baking dish",
      "Beat eggs with remaining milk and pour over the meat",
      "Bake at 350°F for 45 minutes or until set"
    ],
  },
  {
    id: 5,
    name: "Doro Wat",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 120,
    difficulty: 'Medium' as const,
    category: "East African",
    description: "An Ethiopian spicy chicken stew served with injera bread.",
    ingredients: ["2 lbs chicken pieces", "4 onions", "1/4 cup niter kibbeh (spiced butter)", "3 tbsp berbere spice", "4 hard-boiled eggs", "2 lemons", "Salt to taste"],
    instructions: [
      "Marinate chicken in lemon juice for 30 minutes",
      "Caramelize onions in niter kibbeh for 45 minutes",
      "Add berbere spice and cook for 5 minutes",
      "Add chicken and simmer for 40 minutes",
      "Add hard-boiled eggs and cook for 5 more minutes",
      "Serve hot with injera bread"
    ],
  },
  {
    id: 6,
    name: "Moroccan Tagine",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 90,
    difficulty: 'Medium' as const,
    category: "North African",
    description: "A fragrant Moroccan stew cooked in a special pot called a tagine.",
    ingredients: ["1 lb lamb or chicken", "1 onion", "2 carrots", "2 potatoes", "1 cup dried apricots", "1 can chickpeas", "2 tbsp ras el hanout spice mix", "1 cup chicken broth", "Salt to taste"],
    instructions: [
      "Brown meat in oil in the tagine base",
      "Add onions and spices, cook until fragrant",
      "Layer vegetables and apricots on top of the meat",
      "Add broth and chickpeas",
      "Cover and simmer for 1 hour",
      "Serve hot with couscous"
    ],
  },
  {
    id: 7,
    name: "Suya",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 40,
    difficulty: 'Medium' as const,
    category: "West African",
    description: "Spicy grilled meat skewers, a popular Nigerian street food.",
    ingredients: ["1 lb beef sirloin", "2 tbsp ground peanuts", "1 tsp cayenne pepper", "1 tsp paprika", "1 tsp garlic powder", "1 tsp onion powder", "Salt to taste"],
    instructions: [
      "Slice beef into thin strips",
      "Mix spices and ground peanuts to make suya spice",
      "Coat beef strips in suya spice",
      "Thread beef onto skewers",
      "Grill for 5-7 minutes each side",
      "Serve hot with sliced onions and tomatoes"
    ],
  },
  {
    id: 8,
    name: "Shakshuka",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 30,
    difficulty: 'Easy' as const,
    category: "North African",
    description: "Eggs poached in a sauce of tomatoes, peppers, and spices.",
    ingredients: ["6 eggs", "1 can diced tomatoes", "1 onion", "1 red bell pepper", "2 cloves garlic", "1 tsp cumin", "1 tsp paprika", "Salt and pepper to taste"],
    instructions: [
      "Sauté onions and bell pepper until soft",
      "Add garlic and spices, cook for 1 minute",
      "Add tomatoes and simmer for 10 minutes",
      "Make wells in the sauce and crack eggs into them",
      "Cover and cook until eggs are set",
      "Serve hot with bread"
    ],
  },
  {
    id: 9,
    name: "Injera with Doro Wat",
    image: "/placeholder.svg?height=300&width=400",
    prepTime: 180,
    difficulty: 'Hard' as const,
    category: "East African",
    description: "Ethiopian sourdough flatbread served with spicy chicken stew.",
    ingredients: ["For Injera: 2 cups teff flour, water, salt", "For Doro Wat: 2 lbs chicken, 1 cup berbere spice, 6 eggs, 2 onions, 1/4 cup niter kibbeh"],
    instructions: [
      "For Injera: Mix teff flour with water and let ferment for 24 hours",
      "Cook thin layers of batter on a hot griddle",
      "For Doro Wat: Marinate chicken in lemon juice and berbere",
      "Caramelize onions in niter kibbeh",
      "Add chicken and simmer for 40 minutes",
      "Add boiled eggs and cook for 5 more minutes",
      "Serve Doro Wat over Injera"
    ],
  },
]

